logger:
  level: info
  development: false
  disable_caller: false
  disable_stacktrace: false
  encoding: console
  output_paths: [stdout]
  error_output_paths: [stderr]

server:
  host: localhost
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 60s
  max_header_bytes: 1048576
  shutdown_timeout: 5s

auth:
  access_token_ttl: 240h
  refresh_token_ttl: 720h
