name: Linter & Tests

on:
  push:
    branches:
      - "**"
      - "!main"
      - "!master"
  pull_request:
    branches:
      - "**"
      - "!main"
      - "!master"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  tests:
    env:
      CONFIG_NAME: testing1
      AUTH_JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_DRIVER: postgres
      DB_PORT: 5432
      CONTAINER_NAME: notes_app1y_test
      DB_NAME: test-app1y
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: Start docker
        run: make docker-up

      - name: Run tests
        run: make test

      - name: Stop docker
        run: make docker-down

      - name: Check formatting
        run: |
          gofmt -l . | grep . && echo "gofmt found unformatted files" && exit 1 || true